"use client";

import { useMemo, useState } from "react";
import { History } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ConfirmSubmitButton } from "@/components/ui/confirm-submit-button";
import { formatDateTime } from "@/lib/format-date";

export type InvitationStatus = "all" | "open" | "used" | "revoked";

export type InvitationHistoryUser = {
  id: string;
  name: string | null;
  email: string;
};

export type InvitationHistoryItem = {
  id: string;
  code: string;
  note: string | null;
  createdAt: Date | string;
  usedAt: Date | string | null;
  revokedAt: Date | string | null;
  claimedEmail: string | null;
  createdBy: string | null;
  usedBy: string | null;
  creator?: InvitationHistoryUser;
  usedByUser?: InvitationHistoryUser;
};

const invitationStatuses = ["all", "open", "used", "revoked"] as const;

function formatUser(user: InvitationHistoryUser | undefined) {
  if (!user) return "Unknown";
  return `${user.name || "Unnamed user"} <${user.email}>`;
}

function invitationStatusOf(invitation: InvitationHistoryItem): InvitationStatus {
  if (invitation.revokedAt) return "revoked";
  if (invitation.usedAt) return "used";
  return "open";
}

export function InvitationHistoryCard({
  invitations,
  revokeInvitationAction,
}: {
  invitations: InvitationHistoryItem[];
  revokeInvitationAction: (formData: FormData) => Promise<void>;
}) {
  const [filter, setFilter] = useState<InvitationStatus>("all");
  const filteredInvitations = useMemo(
    () =>
      filter === "all"
        ? invitations
        : invitations.filter(
            (invitation) => invitationStatusOf(invitation) === filter,
          ),
    [filter, invitations],
  );

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <History className="size-4" />
          Invitation history
        </CardTitle>
        <CardDescription>
          Last 5 generated codes, who made them, and which account used each
          code.
        </CardDescription>
        <CardAction>
          <div className="flex flex-wrap gap-2">
            {invitationStatuses.map((status) => (
              <Button
                key={status}
                type="button"
                size="sm"
                variant={filter === status ? "default" : "outline"}
                onClick={() => setFilter(status)}
              >
                {status[0].toUpperCase() + status.slice(1)}
              </Button>
            ))}
          </div>
        </CardAction>
      </CardHeader>
      <CardContent className="space-y-3">
        {filteredInvitations.length ? (
          filteredInvitations.map((invitation) => (
            <InvitationRow
              key={invitation.id}
              invitation={invitation}
              revokeInvitationAction={revokeInvitationAction}
            />
          ))
        ) : (
          <p className="text-sm text-muted-foreground">
            No invitation codes match this filter.
          </p>
        )}
      </CardContent>
    </Card>
  );
}

function InvitationRow({
  invitation,
  revokeInvitationAction,
}: {
  invitation: InvitationHistoryItem;
  revokeInvitationAction: (formData: FormData) => Promise<void>;
}) {
  const status = invitationStatusOf(invitation);
  const statusLabel = status[0].toUpperCase() + status.slice(1);

  return (
    <div className="rounded-lg border p-3">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
        <div className="min-w-0 space-y-2">
          <div className="flex flex-wrap items-center gap-2">
            <code className="rounded bg-muted px-2 py-1 text-sm font-semibold">
              {invitation.code}
            </code>
            <span className="rounded-md bg-muted px-1.5 py-0.5 text-xs text-muted-foreground">
              {statusLabel}
            </span>
          </div>
          <div className="grid gap-1 text-sm text-muted-foreground md:grid-cols-2">
            <span>Created {formatDateTime(invitation.createdAt)}</span>
            <span>Generated by {formatUser(invitation.creator)}</span>
            <span>Registered user {formatUser(invitation.usedByUser)}</span>
            <span>Registered {formatDateTime(invitation.usedAt)}</span>
            <span>Revoked {formatDateTime(invitation.revokedAt)}</span>
          </div>
          {!invitation.usedAt && invitation.claimedEmail ? (
            <p className="text-sm text-muted-foreground">
              Registration attempted by {invitation.claimedEmail}
            </p>
          ) : null}
          {invitation.note ? (
            <p className="text-sm text-muted-foreground">{invitation.note}</p>
          ) : null}
        </div>
        {!invitation.usedAt && !invitation.revokedAt ? (
          <form action={revokeInvitationAction}>
            <input type="hidden" name="invitationId" value={invitation.id} />
            <ConfirmSubmitButton
              size="sm"
              variant="outline"
              confirmTitle="Revoke invitation code?"
              confirmDescription={`Code ${invitation.code} will no longer be accepted for registration.`}
              confirmLabel="Revoke"
            >
              Revoke
            </ConfirmSubmitButton>
          </form>
        ) : null}
      </div>
    </div>
  );
}
